### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by fuag15** [StardustXR/stardust-xr#15]
Hey! just trying to check out the WIP. Excited to check it out. Master doesn't run with a no default scn file then a problem with /tmp/c2s not existing and dev i'm not sure how to run. Would it be possible to get some startup instructions? Looks like a cool project, I'm not familiar with godot.

**Comment by technobaboo** [comment]
Hello! Yes this is currently in development and there is not much to show
therefore it won't run without a highly detailed setup process. I'd suggest
watching the repo until I post instructions as there'll be something
interesting to do then :D

**Comment by technobaboo** [comment]
It's been 2 years at this point lol, if you're still having problems feel free to open a new issue though!
